export enum EMulterErrorCode {
  LIMIT_PART_COUNT = 'LIMIT_PART_COUNT',
  LIMIT_FILE_SIZE = 'LIMIT_FILE_SIZE',
  LIMIT_FILE_COUNT = 'LIMIT_FILE_COUNT',
  LIMIT_FIELD_KEY = 'LIMIT_FIELD_KEY',
  LIMIT_FIELD_VALUE = 'LIMIT_FIELD_VALUE',
  LIMIT_FIELD_COUNT = 'LIMIT_FIELD_COUNT',
  LIMIT_UNEXPECTED_FILE = 'LIMIT_UNEXPECTED_FILE',
  MISSING_FIELD_NAME = 'MISSING_FIELD_NAME',
}
